spring.profiles: unittest

spring:
  main:
    show-banner: false
  datasource:
    url: jdbc:mysql://localhost:3306/idstay_development
    username: standalone_user
    password: p@ssword
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create

server:
  port: 8090

flyway:
  enabled: false